version: '3'

services:
  
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'

  db:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql:delegated
    security_opt:
      - seccomp:unconfined
  
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin